version: "3.8"

services:
  api: &api
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - smartpay-network

  db:
    image: mongo@sha256:dac1a094fc6ca3b76efeff9239669a892cc386cdbac7610b9a1c538a2e4f8329
    restart: always
    env_file:
      - ./.env
    volumes:
      - smartpay-dev-db:/data/db
    networks:
      - smartpay-network


volumes:
  smartpay-dev-db:

networks:
  smartpay-network:
    driver: bridge